# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

target 'ML Nav - iOS Sample App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MapLibre', '~> 6.10.0'
  pod 'MapLibreNavigationCore', :path => '../../maplibre-navigation-core/'
  
  pod 'Alamofire', '~> 5.10.2'
  
end
