name: "Validate Gradle Wrapper"

on:
 push:
 pull_request:

jobs:
  validation:
   name: Gradle Wrapper Validation
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: gradle/actions/wrapper-validation@v4
